### ISSUE TITLE
Sending data to neo4j graph db through graylog using neo4j ouptut plugin.

### ISSUE THREAD

**Issue by GaneshbabuRamamoorthy** [zexxon/neo4j-event-console-content-pack#2]
Hi @zexxon 

We are trying to build graph from the server logs. Lets take it as 3 server and every day logs will be generated. the logs will contain source ip, destination ip & messageid. Based on the messageid I am trying to create relationship between the IP Address. We are sending the data to neo4j db from graylog through neo4j output plugin. 

1. Will the everyday data be automatically synced to neo4j?
2. Is there any way to archieve the last 6 days data from neo4j without deleting nodes?

Any suggestions to build the graph based on my requirements?

Regards,
Ganeshbabu R

**Comment by zexxon** [comment]
Hi Ganeshbabu, 

It's been a while since I looked at the Neo4j plugin: 

1. Will the everyday data be automatically synced to neo4j? 

I believe it is an asynchronous process; in that every stream that is associated with the Neo4j output plugin, will be forwarded immediately to Neo4j, as a parameterized Cypher query. 

2. Is there any way to archieve the last 6 days data from neo4j without deleting nodes?

What are your requirements? Do you want a historical graph that allows one to traverse over time? Or do you only want the ability to roll data off after a week, regardless of relationships?

Either can be supported, it's not hard but may require some additional design with respect to the topology model.

I am interested in knowing more about your specific use cases. 

Here is a blog post on the topic, if you haven't already read it: 
https://medium.com/@zexxon/logs-models-and-metrics-how-and-why-they-need-to-be-connected-7c0f8afdd2b7

Thanks,
Matt

**Comment by zexxon** [comment]
Closed due to no response in 3 months. Assuming this is either a non-issue or a solution has been found.
